#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
import dbus
import sys
import dbus.proxies
from subprocess import call
from subprocess import check_output


def main():
    # @type session_bus: dbus.SessionBus
    session_bus = dbus.SessionBus()

    # Check if Skype is running
    system_service_list = session_bus.get_object('org.freedesktop.DBus', '/org/freedesktop/DBus').ListNames()
    skype_api_found = 0

    for service in system_service_list:
        if service == 'com.Skype.API':
            skype_api_found = 1
            break

    if not skype_api_found:
        exit(1)

    # @type skype_service: dbus.proxies.ProxyObject
    skype_service = session_bus.get_object('com.Skype.API', '/com/Skype')
    answer = skype_service.Invoke('Name SkypeApiClient')

    if answer != 'OK':
        sys.exit('Could not bind to Skype client.')

    answer = skype_service.Invoke('PROTOCOL 8')

    if answer != 'PROTOCOL 8':
        sys.exit('This test program only supports Skype API protocol version 1.')    
    
    i = 0

    for arg in sys.argv:
        if arg == 'manual-mode':
            while True:
                cmd = raw_input('Type your command: ')

                if cmd == '' or cmd == '^[':
                    break

                result = skype_service.Invoke(cmd.upper())
                print result + "\n"

        if arg == 'hang-up':
            result = skype_service.Invoke('SEARCH ACTIVECALLS')

            if result[:6] == 'CALLS ':
                for id in result[6:].split(' '):
                    skype_service.Invoke('SET CALL ' + str(id) + ' STATUS FINISHED')
        elif arg == 'pick-up':
            result = skype_service.Invoke('SEARCH ACTIVECALLS')

            if result[:6] == 'CALLS ':
                for id in result[6:].split(' '):
                    skype_service.Invoke('ALTER CALL ' + str(id) + ' ANSWER')
        elif arg == 'missed':
            result = skype_service.Invoke('SEARCH MISSEDCHATS')
            missed_chats = ''

            if result[:6] == 'CHATS ':
                missed_chats = result[6:].split(', ')

            if missed_chats and len(missed_chats[0]):
                skype_service.Invoke('OPEN CHAT ' + str(missed_chats[0]))
        elif arg == 'recent':
            result = skype_service.Invoke('SEARCH RECENTCHATS')

            if result[:6] == 'CHATS ':
                recent_chats = result[6:].split(', ')

                if len(recent_chats) and len(recent_chats[0]):
                    skype_service.Invoke('OPEN CHAT ' + str(recent_chats[0]))
        elif arg == 'contacts':
            try:
                username = sys.argv[i+1]
            except IndexError:
                print('Skype username is not defined.')
                return 1

            focused_window_id = check_output('xdotool getwindowfocus', shell=True)
            result = skype_service.Invoke('GET WINDOWSTATE')

            if result != 'WINDOWSTATE NORMAL':
                skype_service.Invoke('SET WINDOWSTATE NORMAL')

            contacts_window_id = check_output('xdotool search --name "' + str(username) + ' - Skype.*"', shell=True)

            if focused_window_id == contacts_window_id:
                skype_service.Invoke('SET WINDOWSTATE HIDDEN')
            else:
                call('xdotool search --name "'+str(username)+' - Skype." windowactivate', shell=True)
        else:
            skype_service.Invoke(arg)

        i += 1

if __name__ == '__main__':
    main()
